<a href="https://colab.research.google.com/github/weerinphas/CMU/blob/main/640631127_PANDAs_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Descriptive Statistic
[Short Description](https://docs.google.com/presentation/d/1TfJ1BpWhyPgegSpCFntezZo5e6egiKr-aSVgSGu64ww/edit?usp=sharing)

With the given data

In [1]:
import pandas as pd

In [2]:
data = {
    'section 1':[13,8,18.5,8.5,12.5,12,8.5,7.5,6.5,13,14,8.5,8.5,15,11,12.5],
    'section 2':[10,7,12,15,11,13.5,13,13,3,7.5,15,8,11.5,5,10,11],
    'section 3':[16,14,16,15,15,19,15.5,17,12,15,17,15,16,17,14,13],
    'section 4':[12,6.5,12.5,16.5,17,20,10,12,2,5,9,10,18,12.5,7,13]
}
frame = pd.DataFrame(data)
frame

    section 1  section 2  section 3  section 4
0        13.0       10.0       16.0       12.0
1         8.0        7.0       14.0        6.5
2        18.5       12.0       16.0       12.5
3         8.5       15.0       15.0       16.5
4        12.5       11.0       15.0       17.0
5        12.0       13.5       19.0       20.0
6         8.5       13.0       15.5       10.0
7         7.5       13.0       17.0       12.0
8         6.5        3.0       12.0        2.0
9        13.0        7.5       15.0        5.0
10       14.0       15.0       17.0        9.0
11        8.5        8.0       15.0       10.0
12        8.5       11.5       16.0       18.0
13       15.0        5.0       17.0       12.5
14       11.0       10.0       14.0        7.0
15       12.5       11.0       13.0       13.0

to get all the description, use the function describe

![image.png]()

In [3]:
frame.describe()

       section 1  section 2  section 3  section 4
count  16.000000  16.000000  16.000000  16.000000
mean   11.093750  10.343750  15.406250  11.437500
std     3.277289   3.462748   1.705078   4.918926
min     6.500000   3.000000  12.000000   2.000000
25%     8.500000   7.875000  14.750000   8.500000
50%    11.500000  11.000000  15.250000  12.000000
75%    13.000000  13.000000  16.250000  13.875000
max    18.500000  15.000000  19.000000  20.000000

We can get only some described statistic by calling the related methods

![image.png]()

In [4]:
frame.count()

section 1    16
section 2    16
section 3    16
section 4    16
dtype: int64

In addition we can find the described statistic for only some paramter

In [5]:
frame.skew()

section 1    0.579651
section 2   -0.632169
section 3   -0.001486
section 4   -0.074704
dtype: float64

In [6]:
frame.min()

section 1     6.5
section 2     3.0
section 3    12.0
section 4     2.0
dtype: float64

All descriptive funciton which can be called is provided


![image.png]()

In some statisticl data, like correlation, and covariance are compare from pairs of parameter

Let's download the data of the stock prices and volumes obtained from Yahoo! finance and calculate for the covarience

![image.png]()

In [7]:
!pip install --upgrade pandas
!pip install --upgrade pandas-datareader

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.3)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: pandas-datareader in /usr/local/lib/python3.7/dist-packages (0.10.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (4.2.6)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (1.3.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (2.23.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (1.19.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (2021.5.30)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (1.25.11)

In [8]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker) 
            for ticker in ['GOOG','IBM']}

all_data

{'GOOG':                    High          Low  ...   Volume    Adj Close
 Date                                  ...
 2016-09-15   773.799988   759.960022  ...  1305100   771.760010
 2016-09-16   769.750000   764.659973  ...  2049300   768.880005
 2016-09-19   774.000000   764.440979  ...  1172800   765.700012
 2016-09-20   773.330017   768.530029  ...   978600   771.409973
 2016-09-21   777.159973   768.301025  ...  1167800   776.219971
 ...                 ...          ...  ...      ...          ...
 2021-09-08  2911.020020  2884.000000  ...   774300  2897.669922
 2021-09-09  2913.389893  2888.679932  ...   739900  2898.270020
 2021-09-10  2920.379883  2834.830078  ...  1643500  2838.419922
 2021-09-13  2883.820068  2845.649902  ...  1008200  2869.300049
 2021-09-14  2894.550049  2858.110107  ...   659237  2869.520020

 [1258 rows x 6 columns],
 'IBM':                   High         Low  ...     Volume   Adj Close
 Date                                ...
 2016-09-15  156.330002  153.210007  ...  3645600.0  124.282288
 2016-09-16  155.399994  153.470001  ...  6463600.0  122.829163
 2016-09-19  156.190002  154.550003  ...  2450100.0  123.651497
 2016-09-20  156.570007  154.449997  ...  2159100.0  123.316193
 2016-09-21  155.679993  153.869995  ...  2473900.0  124.178482
 ...                ...         ...  ...        ...         ...
 2021-09-08  139.089996  137.600006  ...  2985400.0  138.669998
 2021-09-09  138.960007  137.559998  ...  3508300.0  137.740005
 2021-09-10  139.369995  137.000000  ...  3974100.0  137.020004
 2021-09-13  138.990005  137.509995  ...  4144100.0  138.149994
 2021-09-14  138.550003  135.339996  ...  2672813.0  135.558807

 [1258 rows x 6 columns]}

and then create the data frame of price

![image.png]()

In [9]:
price = pd.DataFrame({ticker:data['Adj Close'] 
                      for ticker,data in all_data.items()})

price

                   GOOG         IBM
Date
2016-09-15   771.760010  124.282288
2016-09-16   768.880005  122.829163
2016-09-19   765.700012  123.651497
2016-09-20   771.409973  123.316193
2016-09-21   776.219971  124.178482
...                 ...         ...
2021-09-08  2897.669922  138.669998
2021-09-09  2898.270020  137.740005
2021-09-10  2838.419922  137.020004
2021-09-13  2869.300049  138.149994
2021-09-14  2869.520020  135.558807

[1258 rows x 2 columns]

and create the data frame of Volume

![image.png]()

In [10]:
price=pd.DataFrame({ticker:data['Volume'] for ticker,data in all_data.items()})

price

               GOOG        IBM
Date
2016-09-15  1305100  3645600.0
2016-09-16  2049300  6463600.0
2016-09-19  1172800  2450100.0
2016-09-20   978600  2159100.0
2016-09-21  1167800  2473900.0
...             ...        ...
2021-09-08   774300  2985400.0
2021-09-09   739900  3508300.0
2021-09-10  1643500  3974100.0
2021-09-13  1008200  4144100.0
2021-09-14   659237  2672813.0

[1258 rows x 2 columns]

The percent changed of each day is calculated as time series (described in later class) is shown as given

![image.png]()

**Hint** tail() function is used to show the last data, the default is 5 data, you may change the number of showed data by add the number you want to show as the input parameter of the tail methods

In [11]:
returns = price.pct_change()
returns.head()

                GOOG       IBM
Date
2016-09-15       NaN       NaN
2016-09-16  0.570225  0.772987
2016-09-19 -0.427707 -0.620939
2016-09-20 -0.165587 -0.118771
2016-09-21  0.193337  0.145801

The corr method, and cov methods will calculate the correlation and covarience of the overlapping, non-NA,
aligned-by-index values in two Series

![image.png]()

![image.png]()

In [12]:
returns['GOOG'].corr(returns['IBM'])

0.3057978172106825

In [13]:
returns['GOOG'].cov(returns['IBM'])

0.061066355341267316

# Described statistic Hand ons

You can get the data frame of exchange rate between THB and USD using the given source code.
The provider of the data is from [Fred, St.Louis Fed](https://fred.stlouisfed.org/), you can search for many data provided by them using the given code and change the reader index to the value you want to get


![image.png]()

In [14]:
thusd = web.get_data_fred('DEXTHUS')

print(thusd)

            DEXTHUS
DATE
2016-09-15    34.90
2016-09-16    34.92
2016-09-19    34.77
2016-09-20    34.76
2016-09-21    34.70
...             ...
2021-09-06      NaN
2021-09-07    32.68
2021-09-08    32.75
2021-09-09    32.71
2021-09-10    32.69

[1302 rows x 1 columns]

In [15]:
thusd.describe()

           DEXTHUS
count  1244.000000
mean     32.223915
std       1.511620
min      29.750000
25%      31.170000
50%      31.880000
75%      33.140000
max      36.010000

Write the code to show the minimum exchnage rate, maximum exchange rate
the standard deriviation, the exchange rate which at percentile 90

In [16]:
# minimum exchnage rate
thusd.min()

DEXTHUS    29.75
dtype: float64

In [17]:
# maximum exchnage rate
thusd.max()

DEXTHUS    36.01
dtype: float64

In [18]:
# the standard deriviation
thusd.std()

DEXTHUS    1.51162
dtype: float64

In [19]:
# the exchange rate which at percentile 90
thusd.describe([.9])

           DEXTHUS
count  1244.000000
mean     32.223915
std       1.511620
min      29.750000
50%      31.880000
90%      34.637000
max      36.010000

get the date which the mininum exchange rate, maximum exchnage rate, and the exchange rate which is at percentilie 90 are

In [20]:
thusd.DEXTHUS[thusd.DEXTHUS==thusd['DEXTHUS'].min()].index.tolist()

# x=thusd['DEXTHUS'].min()
# x

# thusd.DEXTHUS[thusd.DEXTHUS==x].index().tolist()

[Timestamp('2019-12-31 00:00:00')]

In [21]:
# the date which the mininum exchange rate
thusd.idxmin()

DEXTHUS   2019-12-31
dtype: datetime64[ns]

In [22]:
# the date which the maximum exchange rate
thusd.idxmax()

DEXTHUS   2016-12-22
dtype: datetime64[ns]

In [23]:
# the date which at percentile 90
thusd.DEXTHUS[thusd.DEXTHUS==thusd['DEXTHUS'].quantile(0.9)].index.tolist()

[]

**Hint**: to get the index name of the data you need, you can use the code example

In [24]:
import numpy as np
a = pd.DataFrame(np.arange(10).reshape(5,2),columns=['c1','c2'])
# get the list of index name which the value in series c1 is equal to 8
a.c1[a.c1 == 8].index.tolist()

[4]

Loading the gold data from fred (using this data "Gold Fixing Price 10:30 A.M. (London time) in London Bullion Market, based in U.S. Dollars"),
Show the covarience, and correlation of the value the gold price (in US) and the exchange rate. and the covarience, and corelation of the percent change for both of them.

In [25]:
# Loading the gold data from fred
gold = web.get_data_fred('GOLDAMGBD228NLBM')

print(gold)

            GOLDAMGBD228NLBM
DATE
2016-09-15           1320.10
2016-09-16           1314.25
2016-09-19           1315.05
2016-09-20           1315.40
2016-09-21           1319.60
...                      ...
2021-09-07           1810.75
2021-09-08           1797.95
2021-09-09           1795.35
2021-09-10           1799.90
2021-09-13           1787.85

[1303 rows x 1 columns]

In [26]:
# Show the covarience, and correlation of the value the gold price (in US) and the exchange rate
gold['GOLDAMGBD228NLBM'].corr(thusd['DEXTHUS'])

-0.5910995305897309

In [27]:
gold['GOLDAMGBD228NLBM'].cov(thusd['DEXTHUS'])

-223.44957534079225

In [28]:
# Show the covarience, and corelation of the percent change for both of them
gold_changes = gold.pct_change()
gold_changes.head()

            GOLDAMGBD228NLBM
DATE
2016-09-15               NaN
2016-09-16         -0.004431
2016-09-19          0.000609
2016-09-20          0.000266
2016-09-21          0.003193

In [29]:
gold_changes['GOLDAMGBD228NLBM'].corr(thusd['DEXTHUS'])

-0.028785385999290224

In [30]:
gold_changes['GOLDAMGBD228NLBM'].cov(thusd['DEXTHUS'])

-0.0003662891893397277

# Data Loading

Pandas support many data loading scheme and Data sources
---

There are many format that the pandas support

Start by the very simple one, the csv file



---

csv is standed for comma seperate value, the value is seperated by the comma you can see the example [here](https://drive.google.com/drive/folders/1SERgw7Ow98SmnVfF3tsH_JCJa6d56aOr?usp=sharing)

If you used your own computer, you can refer to the file directly, but as we are in the Colab we need to upload the file first. Open the small tap on your left.

![image.png]()

and then select file menuu


![image.png]()

create a new folder name examples, and copy the ex1.csv to the folder

![image.png]()


Now you can see the given file using this command

**Note** the `!` infront of the command means we try to use the linux command, not the python command

In [31]:
!cat examples/ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

Then we create the dataframe from the given csv file

![image.png]()

In [32]:
df = pd.read_csv('examples/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Some file may not contain a header row, for example this [file](https://drive.google.com/open?id=1fuFYVsCFo4vqwbEjvdg9K74Y7HvpsctL)

We can assign default column names

![image.png]()

In [33]:
pd.read_csv('examples/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

or we can set the name ourselves

![image.png]()

In [34]:
pd.read_csv('examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

What if we missed the column name, what will be return?

In [35]:
pd.read_csv('examples/ex2.csv', names=['a', 'b'])

          a      b
1 2  3    4  hello
5 6  7    8  world
9 10 11  12    foo

In [36]:
# The dataframe will set the previous column as an index, and keep the data only last n row that we set the column names

If we want to form the hierachical index from multiple column, you can use the [file](https://drive.google.com/open?id=1mXKSZGxo53IInCL2sWsfHH9EyOOMfeFv), and the code as given

![image.png]()

In [37]:
parsed = pd.read_csv('examples/csv_mindex.csv',
                    index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

To write the csv from pandas, symply use `to_csv` method.

read the data from the example [file](https://drive.google.com/open?id=1B2vyFi3KsY2BWsesPujkX_cb2ZYUcWoV)

In [38]:
data = pd.read_csv('examples/ex3.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

Write out the file

then refrest the Files pane to see the output

![image.png]()

In [39]:
data.to_csv('examples/out.csv')

We can reidirect the output to the console to see the output before writing the file, using the `sys.stdout` instead of the file name
In addition 

We can change the seperator using the given snippet

![image.png]()

and handle with the NaN data using the `na_rep` paramter

![image.png]()

In [40]:
import sys
data.to_csv(sys.stdout, sep='|')
data.to_csv(sys.stdout, na_rep = 'NULL')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo
,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

# Handons loading csv

With the given [file](https://drive.google.com/open?id=1mMDzEoVv-umbnDToczq1W-FHPq7nxAo1), create the DataFrame which is similar to the data frame in 

![image.png]()

In [41]:
data = pd.read_csv('examples/samples.csv', header=None, names=['Section1', 'Section2', 'Section3', 'Section4'])
data

    Section1  Section2  Section3  Section4
0       13.0      10.0      16.0      12.0
1        8.0       7.0      14.0       6.5
2       18.5      12.0      16.0      12.5
3        8.5      15.0      15.0      16.5
4       12.5      11.0      15.0      17.0
5       12.0      13.5      19.0      20.0
6        8.5      13.0      15.5      10.0
7        7.5      13.0      17.0      12.0
8        6.5       3.0      12.0       2.0
9       13.0       7.5      15.0       5.0
10      14.0      15.0      17.0       9.0
11       8.5       8.0      15.0      10.0
12       8.5      11.5      16.0      18.0
13      15.0       5.0      17.0      12.5
14      11.0      10.0      14.0       7.0
15      12.5      11.0      13.0      13.0

and then select only the index which total score (the summation score in section 1,2,3,4 is more than 50 and write out to the file name out1.csv)

In [42]:
data = data[data.sum(axis=1) > 50]
data

    Section1  Section2  Section3  Section4
0       13.0      10.0      16.0      12.0
2       18.5      12.0      16.0      12.5
3        8.5      15.0      15.0      16.5
4       12.5      11.0      15.0      17.0
5       12.0      13.5      19.0      20.0
10      14.0      15.0      17.0       9.0
12       8.5      11.5      16.0      18.0

In [43]:
data.to_csv('out1.csv', index=False)

# Reading the Excel file

One of the popular data source is the excel file
We can get the pandas retrive the data to the data frame for further implementation.

With the [example file](https://drive.google.com/open?id=1XycPSQGocHRTyUK723GDL5nC71hP0cW7), load the file as given

![image.png]()

In [44]:
!pip install openpyxl==3.0.5

Requirement already satisfied: openpyxl==3.0.5 in /usr/local/lib/python3.7/dist-packages (3.0.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl==3.0.5) (1.1.0)
Requirement already satisfied: jdcal in /usr/local/lib/python3.7/dist-packages (from openpyxl==3.0.5) (1.4.1)

In [45]:
xlsx = pd.ExcelFile('examples/ex1.xlsx')

Then we have to select which sheet we want to retrieve data

![image.png]()

In [46]:
df = pd.read_excel(xlsx, 'Sheet1')
df

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

The unnamed: column is shown as there is some special data is stored in the excel file, so we can filter it using the given code

![image.png]()

In [47]:
df = df[df.filter(regex='^(?!Unnamed)').columns]
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Or we can make the read_excel shorter than call 2 times as given

![image.png]()

In [48]:
frame = pd.read_excel('examples/ex1.xlsx', 'Sheet1')
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

If the data frame is in the first row, and first column, we can specified the start row, and column.
For example, the given [file](https://drive.google.com/open?id=1FAwZewZknR-eQKTVJELoVrpKdpxjEQ1U)

![image.png]()

In [49]:
frame = pd.read_excel('examples/samples.xlsx', sheet_name='Sheet1',
                      index_col=0,usecols="B:K",

                      skiprows=4,nrows=33)
frame

                     Name        Last Name  ...      Total  Grade
ID                                          ...
492115002        KANNIGA             SAGON  ...  42.442188      D
492115003          KASIN      VISRUTAVANIJ  ...  50.252604      C
492115004       KITTIKUN         PANSAILOM  ...  50.482292      C
492115007        KANITTA        MOONLAPONG  ...  75.513021      A
492115008        JARUWAN         WANNAGOAT  ...  58.856250     C+
492115009       JIRAPHAT            JOKDEE  ...  70.621354      A
492115010        JENJIRA           JAIMUNK  ...  63.058333      B
492115012      CHOMPUNUT            SOIJIT  ...  68.235938     B+
492115014          THITI           SUNUNTA  ...  61.077083      B
492115015      NATTAKORN          KIRDKAEW  ...  60.044271      B
492115016     NATTHAPONG             IWANA  ...  55.562500     C+
492115017     NUTTAWADEE        SURIYANUNT  ...  45.726042     D+
492115018        SONGSAK             MAMEA  ...  42.882812      D
492115021        TANAKORN    TACHAWUTTIPAT  ...  56.407812     C+
492115022        TISINEE          SURAPUNT  ...  63.773958      B
492115023      THEERAPAT   SRITHARATHIKHUN  ...  68.721875     B+
492115024       NOOTSARA           INTAPUN  ...  64.503646      B
492115027      PONGPIJIT     UTTRAMAPOKRAY  ...  55.633333     C+
492115030        PANUWAT        THEEKAPORN  ...  56.708333     C+
492115031       PANUPONG     BANDITPURITAT  ...  63.362500      B
492115032        PAWINEE            SUBPAN  ...  58.847396     C+
492115034        PEERAWAT          POOMBUA  ...  57.443229     C+
492115035       MAYSINEE       CHANACHOMPU  ...  52.291146      C
492115036       RAPIPORN        BANJAREARN  ...  54.134375      C
492115037       WARITSARA           JITMUN  ...  55.265104     C+
492115038       WALAILUCK     SUWANNASOPON  ...  53.661458      C
492115039  WATCHARAPONG            MOONRIN  ...  71.870833      A
492115040       SIWAPORN       MANOCHOMPHU  ...  55.731250     C+
492115041      SUTTIPONG            INTAYA  ...  72.044792      A
492115042      SUTTIPONG      PUNYAWORASIN  ...  51.817188      C
492115043      SUPAPORN             KOMLUE  ...  48.519792     D+
492115044         SURAKIT           SUKJUN  ...  54.992188      C
492115045       APITCHAKA          SINGJAI  ...  51.980729      C

[33 rows x 9 columns]

**Hint,** to show all row you may set it by
![image.png]()

The default value is 10

In [50]:
pd.set_option('display.max_rows', None)
frame

                     Name        Last Name  ...      Total  Grade
ID                                          ...
492115002        KANNIGA             SAGON  ...  42.442188      D
492115003          KASIN      VISRUTAVANIJ  ...  50.252604      C
492115004       KITTIKUN         PANSAILOM  ...  50.482292      C
492115007        KANITTA        MOONLAPONG  ...  75.513021      A
492115008        JARUWAN         WANNAGOAT  ...  58.856250     C+
492115009       JIRAPHAT            JOKDEE  ...  70.621354      A
492115010        JENJIRA           JAIMUNK  ...  63.058333      B
492115012      CHOMPUNUT            SOIJIT  ...  68.235938     B+
492115014          THITI           SUNUNTA  ...  61.077083      B
492115015      NATTAKORN          KIRDKAEW  ...  60.044271      B
492115016     NATTHAPONG             IWANA  ...  55.562500     C+
492115017     NUTTAWADEE        SURIYANUNT  ...  45.726042     D+
492115018        SONGSAK             MAMEA  ...  42.882812      D
492115021        TANAKORN    TACHAWUTTIPAT  ...  56.407812     C+
492115022        TISINEE          SURAPUNT  ...  63.773958      B
492115023      THEERAPAT   SRITHARATHIKHUN  ...  68.721875     B+
492115024       NOOTSARA           INTAPUN  ...  64.503646      B
492115027      PONGPIJIT     UTTRAMAPOKRAY  ...  55.633333     C+
492115030        PANUWAT        THEEKAPORN  ...  56.708333     C+
492115031       PANUPONG     BANDITPURITAT  ...  63.362500      B
492115032        PAWINEE            SUBPAN  ...  58.847396     C+
492115034        PEERAWAT          POOMBUA  ...  57.443229     C+
492115035       MAYSINEE       CHANACHOMPU  ...  52.291146      C
492115036       RAPIPORN        BANJAREARN  ...  54.134375      C
492115037       WARITSARA           JITMUN  ...  55.265104     C+
492115038       WALAILUCK     SUWANNASOPON  ...  53.661458      C
492115039  WATCHARAPONG            MOONRIN  ...  71.870833      A
492115040       SIWAPORN       MANOCHOMPHU  ...  55.731250     C+
492115041      SUTTIPONG            INTAYA  ...  72.044792      A
492115042      SUTTIPONG      PUNYAWORASIN  ...  51.817188      C
492115043      SUPAPORN             KOMLUE  ...  48.519792     D+
492115044         SURAKIT           SUKJUN  ...  54.992188      C
492115045       APITCHAKA          SINGJAI  ...  51.980729      C

[33 rows x 9 columns]

In [51]:
pd.set_option('display.max_rows', 10)
frame

                 Name     Last Name  ...      Total  Grade
ID                                   ...
492115002    KANNIGA          SAGON  ...  42.442188      D
492115003      KASIN   VISRUTAVANIJ  ...  50.252604      C
492115004   KITTIKUN      PANSAILOM  ...  50.482292      C
492115007    KANITTA     MOONLAPONG  ...  75.513021      A
492115008    JARUWAN      WANNAGOAT  ...  58.856250     C+
...               ...           ...  ...        ...    ...
492115041  SUTTIPONG         INTAYA  ...  72.044792      A
492115042  SUTTIPONG   PUNYAWORASIN  ...  51.817188      C
492115043  SUPAPORN          KOMLUE  ...  48.519792     D+
492115044     SURAKIT        SUKJUN  ...  54.992188      C
492115045   APITCHAKA       SINGJAI  ...  51.980729      C

[33 rows x 9 columns]

# Getting data from Web APIs

Some web site provide the WebAPIs which we can receive data using json object
Try to click on this [link](https://api.github.com/repos/pandas-dev/pandas/issues)

you will see the list of last 30 GitHub issue for pandas on Github,
we can add read the data using the Python as given

![image.png]()

In [52]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

The response object show the response code (200 means it is successfully downloaded)

To read the data which come with it. Use the json method

![image.png]()

In [53]:
data = resp.json()
data

[{'active_lock_reason': None,
  'assignee': None,
  'assignees': [],
  'author_association': 'CONTRIBUTOR',
  'body': '…(#25781)\r\n\r\n- [x] closes #25781\r\n- [x] tests added / passed\r\n- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them\r\n- [ ] whatsnew entry\r\n',
  'closed_at': None,
  'comments': 0,
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43569/comments',
  'created_at': '2021-09-14T16:00:34Z',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43569/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/43569',
  'id': 996184402,
  'labels': [],
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43569/labels{/name}',
  'locked': False,
  'milestone': None,
  'node_id': 'PR_kwDOAA0YD84rvTI-',
  'number': 43569,
  'performed_via_github_app': None,
  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/43569.diff',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/43569',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/43569.patch',
   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43569'},
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'state': 'open',
  'title': 'BUG: Allow pairwise calcuation when comparing the column with itself …',
  'updated_at': '2021-09-14T16:00:34Z',
  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43569',
  'user': {'avatar_url': 'https://avatars.githubusercontent.com/u/13047435?v=4',
   'events_url': 'https://api.github.com/users/peterpanmj/events{/privacy}',
   'followers_url': 'https://api.github.com/users/peterpanmj/followers',
   'following_url': 'https://api.github.com/users/peterpanmj/following{/other_user}',
   'gists_url': 'https://api.github.com/users/peterpanmj/gists{/gist_id}',
   'gravatar_id': '',
   'html_url': 'https://github.com/peterpanmj',
   'id': 13047435,
   'login': 'peterpanmj',
   'node_id': 'MDQ6VXNlcjEzMDQ3NDM1',
   'organizations_url': 'https://api.github.com/users/peterpanmj/orgs',
   'received_events_url': 'https://api.github.com/users/peterpanmj/received_events',
   'repos_url': 'https://api.github.com/users/peterpanmj/repos',
   'site_admin': False,
   'starred_url': 'https://api.github.com/users/peterpanmj/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/peterpanmj/subscriptions',
   'type': 'User',
   'url': 'https://api.github.com/users/peterpanmj'}},
 {'active_lock_reason': None,
  'assignee': None,
  'assignees': [],
  'author_association': 'MEMBER',
  'body': 'From https://github.com/dask/dask/issues/8137\r\n\r\nOne of the corner cases in groupby apply (discussed in other issues like https://github.com/pandas-dev/pandas/pull/34998) has changed behaviour:\r\n\r\n```python\r\nimport pandas as pd\r\ndf = pd._testing.makeTimeDataFrame()\r\ndf.groupby(df.index.month).apply(lambda x: x.drop_duplicates())\r\n```\r\n\r\nIn pandas 1.3.2 this gives:\r\n\r\n```\r\n                     A         B         C         D\r\n1 2000-01-03 -1.261522 -0.200411 -0.746305 -0.661842\r\n  2000-01-04  1.248556  0.256573 -1.401839  0.508941\r\n  2000-01-05 -0.036682  0.109758 -0.759474 -0.601479\r\n  2000-01-06 -0.778714 -0.932903 -0.544291 -0.986584\r\n  2000-01-07 -0.567276  0.744036  1.981160  0.222988\r\n  2000-01-10 -0.448542  0.221418  0.485706 -1.142561\r\n  2000-01-11 -0.125143 -1.393151  0.879428  0.011297\r\n  2000-01-12  0.550527 -1.373356  1.149654 -0.575065\r\n  2000-01-13  0.269579 -0.017307 -1.023269  0.738274\r\n  2000-01-14  0.757235 -1.875451 -0.751026  0.812741\r\n  2000-01-17  2.456978  0.992319  0.945757 -2.468437\r\n  2000-01-18 -2.132953  1.210491  0.150581 -1.861079\r\n  2000-01-19  0.500947 -0.861651  0.412729 -1.274573\r\n  2000-01-20  0.215823 -0.502341 -0.060564  0.439930\r\n  2000-01-21  0.454649  1.188960  1.167487 -0.087031\r\n  2000-01-24 -1.194599  0.709980  1.927664 -1.868195\r\n  2000-01-25 -1.465017  1.187098  0.262209  0.312123\r\n  2000-01-26 -0.010187 -0.624253 -0.186090 -0.126192\r\n  2000-01-27 -0.520074 -0.189463 -0.379236 -0.259591\r\n  2000-01-28 -1.179406 -0.169766 -1.731189  0.583444\r\n  2000-01-31  0.677903  0.845305 -0.282444  0.807889\r\n2 2000-02-01 -1.561435  2.068383 -0.500742 -0.040578\r\n  2000-02-02 -1.357882  1.302612  1.105816 -0.688315\r\n  2000-02-03  0.604455  0.637055 -0.296199  0.699753\r\n  2000-02-04  0.102784 -0.786359 -0.598806  0.604410\r\n  2000-02-07  0.977317  0.530884 -0.880909 -0.963008\r\n  2000-02-08  1.948681  0.065753 -0.530815 -1.688043\r\n  2000-02-09  1.461333  1.105021  1.039801 -0.144059\r\n  2000-02-10  2.105116 -1.121452  0.076824 -0.334885\r\n  2000-02-11  0.984281  0.858620  1.602277 -0.421881\r\n```\r\n\r\nwhile in pandas 1.3.3 it gives:\r\n\r\n```\r\n                   A         B         C         D\r\n2000-01-03  0.131780  0.079102 -2.631289  0.969882\r\n2000-01-04  0.381887  0.177194 -0.031367 -1.062184\r\n2000-01-05 -1.299994  0.951530  0.806066  1.043698\r\n2000-01-06 -0.669137  1.036442  0.762052 -0.475059\r\n2000-01-07  0.498415 -0.511591 -0.500675  0.098846\r\n2000-01-10 -1.313268  0.511975 -0.935800 -0.371694\r\n2000-01-11  1.812837 -0.017126 -0.748976  1.217975\r\n2000-01-12  0.236695  0.012316  0.319136  0.743945\r\n2000-01-13 -1.128511  0.367611 -0.240936 -0.847221\r\n2000-01-14 -2.170718  1.349021 -1.205040  1.210471\r\n2000-01-17  0.220773  1.238868 -0.208188 -0.240763\r\n2000-01-18 -0.949992  0.273480  0.863710  2.446306\r\n2000-01-19  0.622379  1.386699 -1.181249  0.188620\r\n2000-01-20 -1.340407 -0.523331 -1.794468  0.877138\r\n2000-01-21  0.029993 -0.115333  0.358685  1.652006\r\n2000-01-24  1.209907 -1.354522  0.883701  0.686492\r\n2000-01-25 -0.840201  1.415816  0.396826  1.342700\r\n2000-01-26  1.206150 -0.114443  0.011106  0.995629\r\n2000-01-27 -0.505894  0.500736  0.004411  0.807632\r\n2000-01-28  0.117852 -0.411066  1.315072  0.731249\r\n2000-01-31 -0.329046 -1.921455  2.564603 -0.222591\r\n2000-02-01  0.295899 -0.169977  0.162310 -0.554688\r\n2000-02-02 -1.144224  0.530313 -0.530216  0.287826\r\n2000-02-03  1.491748 -1.051309  1.414135 -0.332648\r\n2000-02-04 -0.452243 -0.087787 -0.308278  0.681506\r\n2000-02-07 -1.041728 -0.202066  0.044722  0.665914\r\n2000-02-08  0.712994  1.547563  2.557823 -0.801031\r\n2000-02-09  0.396298 -1.325411 -0.926420  0.738052\r\n2000-02-10  0.460109  0.734418  0.416767 -1.199427\r\n2000-02-11 -0.104655 -0.440354 -0.787402  0.357853\r\n```\r\n\r\n(note the difference in index)\r\n',
  'closed_at': None,
  'comments': 1,
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43568/comments',
  'created_at': '2021-09-14T15:42:41Z',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43568/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/43568',
  'id': 996167564,
  'labels': [{'color': '729FCF',
    'default': False,
    'description': None,
    'id': 233160,
    'name': 'Groupby',
    'node_id': 'MDU6TGFiZWwyMzMxNjA=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby'},
   {'color': 'e11d21',
    'default': False,
    'description': 'Functionality that used to work in a prior pandas version',
    'id': 32815646,
    'name': 'Regression',
    'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression'}],
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43568/labels{/name}',
  'locked': False,
  'milestone': {'closed_at': None,
   'closed_issues': 7,
   'created_at': '2021-09-10T19:48:56Z',
   'creator': {'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4',
    'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
    'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
    'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
    'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
    'gravatar_id': '',
    'html_url': 'https://github.com/simonjayhawkins',
    'id': 13159005,
    'login': 'simonjayhawkins',
    'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
    'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
    'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',
    'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
    'site_admin': False,
    'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
    'type': 'User',
    'url': 'https://api.github.com/users/simonjayhawkins'},
   'description': 'on-merge: backport to 1.3.x',
   'due_on': '2021-10-17T07:00:00Z',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/90',
   'id': 7142224,
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/90/labels',
   'node_id': 'MI_kwDOAA0YD84AbPtQ',
   'number': 90,
   'open_issues': 42,
   'state': 'open',
   'title': '1.3.4',
   'updated_at': '2021-09-14T16:09:19Z',
   'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/90'},
  'node_id': 'I_kwDOAA0YD847YE-M',
  'number': 43568,
  'performed_via_github_app': None,
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'state': 'open',
  'title': 'REGR: change in output of groupby.apply in 1.3.2 -> 1.3.3',
  'updated_at': '2021-09-14T16:55:45Z',
  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43568',
  'user': {'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4',
   'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}',
   'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers',
   'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}',
   'gravatar_id': '',
   'html_url': 'https://github.com/jorisvandenbossche',
   'id': 1020496,
   'login': 'jorisvandenbossche',
   'node_id': 'MDQ6VXNlcjEwMjA0OTY=',
   'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs',
   'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events',
   'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos',
   'site_admin': False,
   'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions',
   'type': 'User',
   'url': 'https://api.github.com/users/jorisvandenbossche'}},
 {'active_lock_reason': None,
  'assignee': None,
  'assignees': [],
  'author_association': 'NONE',
  'body': "#### Is your feature request related to a problem?\r\n\r\nI am using pandas lib to read xml for further processes, however a number of columns with leading ZERO are always converted to numbers, so I lost the original data.\r\n\r\n#### Describe the solution you'd like\r\n\r\nIt would be great to add **dtype/converter** arguments for `pandas.read_xml()` to force pandas to interprete certain columns with given dtype/converters.\r\nJust like similar IO read (read_csv, read_html, etc)\r\n\r\n[read_xml](https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html)\r\n[read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)\r\n\r\n#### API breaking implications\r\n\r\nProbably not, this argument could be optional.\r\n\r\n#### Describe alternatives you've considered\r\n\r\nWrite my own code to pull data by each xml nodes, which results in very bad performance.",
  'closed_at': None,
  'comments': 0,
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43567/comments',
  'created_at': '2021-09-14T14:38:43Z',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43567/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/43567',
  'id': 996099601,
  'labels': [{'color': '4E9A06',
    'default': False,
    'description': None,
    'id': 76812,
    'name': 'Enhancement',
    'node_id': 'MDU6TGFiZWw3NjgxMg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement'},
   {'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member',
    'id': 1954720290,
    'name': 'Needs Triage',
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage'}],
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43567/labels{/name}',
  'locked': False,
  'milestone': None,
  'node_id': 'I_kwDOAA0YD847X0YR',
  'number': 43567,
  'performed_via_github_app': None,
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'state': 'open',
  'title': 'ENH: Possible to add dtype/converters as arguments for pandas.read_xml() ?',
  'updated_at': '2021-09-14T14:39:00Z',
  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43567',
  'user': {'avatar_url': 'https://avatars.githubusercontent.com/u/46142545?v=4',
   'events_url': 'https://api.github.com/users/soliujing/events{/privacy}',
   'followers_url': 'https://api.github.com/users/soliujing/followers',
   'following_url': 'https://api.github.com/users/soliujing/following{/other_user}',
   'gists_url': 'https://api.github.com/users/soliujing/gists{/gist_id}',
   'gravatar_id': '',
   'html_url': 'https://github.com/soliujing',
   'id': 46142545,
   'login': 'soliujing',
   'node_id': 'MDQ6VXNlcjQ2MTQyNTQ1',
   'organizations_url': 'https://api.github.com/users/soliujing/orgs',
   'received_events_url': 'https://api.github.com/users/soliujing/received_events',
   'repos_url': 'https://api.github.com/users/soliujing/repos',
   'site_admin': False,
   'starred_url': 'https://api.github.com/users/soliujing/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/soliujing/subscriptions',
   'type': 'User',
   'url': 'https://api.github.com/users/soliujing'}},
 {'active_lock_reason': None,
  'assignee': None,
  'assignees': [],
  'author_association': 'NONE',
  'body': "### \n\n- [X] I have checked that this issue has not already been reported.\n\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [x] I have confirmed this bug exists on the master branch of pandas.\n\n\n### Reproducible Example\n\n```python\ns = pd.DataFrame({'s':['aaa', 'bbb', 'ccc']})\r\nprint(f'Initial df bytes {s.memory_usage(deep=True, index=False).sum()}')\r\n# Initial df bytes 180\r\ns = s.assign(s=s.s.astype('string[pyarrow]'))\r\nprint(f'pyarrow string df bytes {s.memory_usage(deep=True, index=False).sum()}')\r\n# pyarrow string df bytes 25\r\ns.to_feather('s.feather')\r\ns = pd.read_feather('s.feather')\r\nprint(f'after feather bytes {s.memory_usage(deep=True, index=False).sum()}')\r\n# after feather bytes 180\n```\n\n\n### Issue Description\n\nLoading a df that contains a column of type string[pyarrow] from a feather file loads the column as type string\n\n### Expected Behavior\n\nLoad the column in its original string[pyarrow] type\n\n### Installed Versions\n\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b\r\npython           : 3.9.6.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 20.4.0\r\nVersion          : Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.UTF-8\r\n\r\npandas           : 1.3.2\r\nnumpy            : 1.21.2\r\npytz             : 2021.1\r\ndateutil         : 2.8.2\r\npip              : 21.2.4\r\nsetuptools       : 52.0.0.post20210125\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.1\r\nIPython          : 7.27.0\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : 2021.08.1\r\nfastparquet      : None\r\ngcsfs            : 2021.08.1\r\nmatplotlib       : 3.4.3\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 5.0.0\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.7.1\r\nsqlalchemy       : 1.4.23\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None\r\n\r\n\r\n</details>\r\n",
  'closed_at': None,
  'comments': 0,
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43565/comments',
  'created_at': '2021-09-14T11:48:18Z',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43565/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/43565',
  'id': 995923285,
  'labels': [{'color': 'e10c02',
    'default': False,
    'description': None,
    'id': 76811,
    'name': 'Bug',
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug'},
   {'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member',
    'id': 1954720290,
    'name': 'Needs Triage',
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage'}],
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43565/labels{/name}',
  'locked': False,
  'milestone': None,
  'node_id': 'I_kwDOAA0YD847XJVV',
  'number': 43565,
  'performed_via_github_app': None,
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'state': 'open',
  'title': 'BUG: string[pyarrow] dtype not loaded from feather',
  'updated_at': '2021-09-14T14:14:58Z',
  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/43565',
  'user': {'avatar_url': 'https://avatars.githubusercontent.com/u/4047665?v=4',
   'events_url': 'https://api.github.com/users/shulmaneyal/events{/privacy}',
   'followers_url': 'https://api.github.com/users/shulmaneyal/followers',
   'following_url': 'https://api.github.com/users/shulmaneyal/following{/other_user}',
   'gists_url': 'https://api.github.com/users/shulmaneyal/gists{/gist_id}',
   'gravatar_id': '',
   'html_url': 'https://github.com/shulmaneyal',
   'id': 4047665,
   'login': 'shulmaneyal',
   'node_id': 'MDQ6VXNlcjQwNDc2NjU=',
   'organizations_url': 'https://api.github.com/users/shulmaneyal/orgs',
   'received_events_url': 'https://api.github.com/users/shulmaneyal/received_events',
   'repos_url': 'https://api.github.com/users/shulmaneyal/repos',
   'site_admin': False,
   'starred_url': 'https://api.github.com/users/shulmaneyal/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/shulmaneyal/subscriptions',
   'type': 'User',
   'url': 'https://api.github.com/users/shulmaneyal'}},
 {'active_lock_reason': None,
  'assignee': None,
  'assignees': [],
  'author_association': 'NONE',

To filter the data, The json is similar to the list of map data structure, we use the index, and key to get the data

![image.png]()

In [54]:
data[0]['title']

'BUG: Allow pairwise calcuation when comparing the column with itself …'

So we can create the the dataframe from the given json object

![image.png]()

In [55]:
issues = pd.DataFrame(data, columns=['number', 'title',
                                     'labels', 'state'])
issues

    number  ... state
0    43569  ...  open
1    43568  ...  open
2    43567  ...  open
3    43565  ...  open
4    43564  ...  open
..     ...  ...   ...
25   43486  ...  open
26   43485  ...  open
27   43483  ...  open
28   43480  ...  open
29   43472  ...  open

[30 rows x 4 columns]

Getting data from other source
---
Pandas provide the tools to get historic data from many remote data source [link text](https://pydata.github.io/pandas-datareader/remote_data.html)
Some of them required the key, some are not. You can see the usage in the given link.


![image.png]()

What you have to do is just add the code to the correct provider

The list of datasource is also [shown](https://github.com/wilsonfreitas/awesome-quant#data-sources)

# Getting Data from other resources

We can get the data from any web services as well
See the example of getting the [Bank Of Thailand example](https://apiportal.bot.or.th/bot/public/)

In [56]:
import requests


url = "https://apigw1.bot.or.th/bot/public/DepositRate/v2/deposit_rate_/"
headers = {
    'x-ibm-client-id': "f065ef48-c8d3-4392-a79a-5387789a78da",
    'accept': "application/json"
    }

resp = requests.request("GET", url, headers=headers, params={"start_period":"2021-08-01", "end_period":"2021-08-31"})

In [57]:
res_j = pd.io.json.loads(resp.text)
print(type(res_j))
res_j

<class 'dict'>

{'result': {'api': 'Deposit Interest Rates for Individuals of Commercial Banks (Percent per annum)',
  'data': {'data_detail': [{'bank_name_eng': 'Bangkok Bank',
     'bank_name_th': 'กรุงเทพ',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.5000',
     'fix_12_mths_min': '0.5000',
     'fix_24_mths_max': '0.5000',
     'fix_24_mths_min': '0.5000',
     'fix_3_mths_max': '0.3750',
     'fix_3_mths_min': '0.3750',
     'fix_6_mths_max': '0.5000',
     'fix_6_mths_min': '0.5000',
     'period': '2021-08-02',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'Krung Thai Bank',
     'bank_name_th': 'กรุงไทย',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.4000',
     'fix_12_mths_min': '0.4000',
     'fix_24_mths_max': '0.4500',
     'fix_24_mths_min': '0.4500',
     'fix_3_mths_max': '0.3200',
     'fix_3_mths_min': '0.3200',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-02',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'Kasikornbank',
     'bank_name_th': 'กสิกรไทย',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.4000',
     'fix_12_mths_min': '0.4000',
     'fix_24_mths_max': '0.4500',
     'fix_24_mths_min': '0.4500',
     'fix_3_mths_max': '0.3200',
     'fix_3_mths_min': '0.3200',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-02',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'The Siam Commercial Bank',
     'bank_name_th': 'ไทยพาณิชย์',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.4000',
     'fix_12_mths_min': '0.4000',
     'fix_24_mths_max': '0.4500',
     'fix_24_mths_min': '0.4500',
     'fix_3_mths_max': '0.3200',
     'fix_3_mths_min': '0.3200',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-02',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'Bank of Ayudhya',
     'bank_name_th': 'กรุงศรีอยุธยา',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.4000',
     'fix_12_mths_min': '0.4000',
     'fix_24_mths_max': '0.4500',
     'fix_24_mths_min': '0.4500',
     'fix_3_mths_max': '0.3200',
     'fix_3_mths_min': '0.3200',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-02',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'TMBThanachart Bank Public Company Limited',
     'bank_name_th': 'ทหารไทยธนชาต',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.6000',
     'fix_12_mths_min': '0.6000',
     'fix_24_mths_max': '0.6000',
     'fix_24_mths_min': '0.6000',
     'fix_3_mths_max': '0.4000',
     'fix_3_mths_min': '0.4000',
     'fix_6_mths_max': '0.5000',
     'fix_6_mths_min': '0.5000',
     'period': '2021-08-02',
     'saving_max': '0.1250',
     'saving_min': '0.1250'},
    {'bank_name_eng': 'United Overseas Bank (Thai) Company Ltd.',
     'bank_name_th': 'ยูโอบี',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.5000',
     'fix_12_mths_min': '0.5000',
     'fix_24_mths_max': '0.6000',
     'fix_24_mths_min': '0.6000',
     'fix_3_mths_max': '0.4000',
     'fix_3_mths_min': '0.4000',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-02',
     'saving_max': '0.2000',
     'saving_min': '0.2000'},
    {'bank_name_eng': 'CIMB  THAI  Bank',
     'bank_name_th': 'ซีไอเอ็มบี ไทย',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.7500',
     'fix_12_mths_min': '0.7500',
     'fix_24_mths_max': '0.8000',
     'fix_24_mths_min': '0.8000',
     'fix_3_mths_max': '0.5000',
     'fix_3_mths_min': '0.5000',
     'fix_6_mths_max': '0.6000',
     'fix_6_mths_min': '0.6000',
     'period': '2021-08-02',
     'saving_max': '0.2000',
     'saving_min': '0.2000'},
    {'bank_name_eng': 'Standard Chartered Bank (Thai)',
     'bank_name_th': 'สแตนดาร์ดชาร์เตอร์ด (ไทย)',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '',
     'fix_12_mths_min': '',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '',
     'fix_3_mths_min': '',
     'fix_6_mths_max': '',
     'fix_6_mths_min': '',
     'period': '2021-08-02',
     'saving_max': '',
     'saving_min': ''},
    {'bank_name_eng': 'TISCO Bank',
     'bank_name_th': 'ทิสโก้',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.8500',
     'fix_12_mths_min': '0.8500',
     'fix_24_mths_max': '0.9500',
     'fix_24_mths_min': '0.9500',
     'fix_3_mths_max': '0.6500',
     'fix_3_mths_min': '0.6500',
     'fix_6_mths_max': '0.7000',
     'fix_6_mths_min': '0.7000',
     'period': '2021-08-02',
     'saving_max': '2.0000',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'Mega International Commercial Bank',
     'bank_name_th': 'เมกะ สากลพาณิชย์',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.7500',
     'fix_12_mths_min': '0.5000',
     'fix_24_mths_max': '0.7500',
     'fix_24_mths_min': '0.7500',
     'fix_3_mths_max': '0.6000',
     'fix_3_mths_min': '0.3000',
     'fix_6_mths_max': '0.7000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-02',
     'saving_max': '0.1250',
     'saving_min': '0.1250'},
    {'bank_name_eng': 'Kiatnakin Phatra Bank',
     'bank_name_th': 'เกียรตินาคินภัทร',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.9000',
     'fix_12_mths_min': '0.7500',
     'fix_24_mths_max': '0.9500',
     'fix_24_mths_min': '0.8000',
     'fix_3_mths_max': '0.6500',
     'fix_3_mths_min': '0.5000',
     'fix_6_mths_max': '0.7000',
     'fix_6_mths_min': '0.5500',
     'period': '2021-08-02',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'Land and Houses  Bank',
     'bank_name_th': 'แลนด์ แอนด์ เฮ้าส์ ',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '1.0500',
     'fix_12_mths_min': '1.0500',
     'fix_24_mths_max': '1.1000',
     'fix_24_mths_min': '1.1000',
     'fix_3_mths_max': '0.8500',
     'fix_3_mths_min': '0.8500',
     'fix_6_mths_max': '0.9500',
     'fix_6_mths_min': '0.9500',
     'period': '2021-08-02',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'Industrial and Commercial Bank of China (Thai)',
     'bank_name_th': 'ไอซีบีซี (ไทย)',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.9500',
     'fix_12_mths_min': '0.9500',
     'fix_24_mths_max': '1.0000',
     'fix_24_mths_min': '1.0000',
     'fix_3_mths_max': '0.7000',
     'fix_3_mths_min': '0.7000',
     'fix_6_mths_max': '0.8000',
     'fix_6_mths_min': '0.8000',
     'period': '2021-08-02',
     'saving_max': '1.0000',
     'saving_min': '0.3500'},
    {'bank_name_eng': 'The Thai Credit Retail Bank',
     'bank_name_th': 'ไทยเครดิตเพื่อรายย่อย',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '1.3500',
     'fix_12_mths_min': '1.2000',
     'fix_24_mths_max': '1.3000',
     'fix_24_mths_min': '1.3000',
     'fix_3_mths_max': '0.9500',
     'fix_3_mths_min': '0.9500',
     'fix_6_mths_max': '1.0000',
     'fix_6_mths_min': '1.0000',
     'period': '2021-08-02',
     'saving_max': '0.4000',
     'saving_min': '0.4000'},
    {'bank_name_eng': 'Bank of China (Thai)',
     'bank_name_th': 'แห่งประเทศจีน(ไทย)',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.5000',
     'fix_12_mths_min': '0.5000',
     'fix_24_mths_max': '0.5000',
     'fix_24_mths_min': '0.5000',
     'fix_3_mths_max': '0.3750',
     'fix_3_mths_min': '0.3750',
     'fix_6_mths_max': '0.5000',
     'fix_6_mths_min': '0.5000',
     'period': '2021-08-02',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'ANZ Bank (Thai) Public Company Limited',
     'bank_name_th': 'ธนาคารเอเอ็นแซด (ไทย) จำกัด (มหาชน)',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '',
     'fix_12_mths_min': '',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '',
     'fix_3_mths_min': '',
     'fix_6_mths_max': '',
     'fix_6_mths_min': '',
     'period': '2021-08-02',
     'saving_max': '',
     'saving_min': ''},
    {'bank_name_eng': 'Sumitomo Mitsui Trust Bank (Thai) ',
     'bank_name_th': 'ซูมิโตโม มิตซุย ทรัสต์  (ไทย)',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '',
     'fix_12_mths_min': '',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '',
     'fix_3_mths_min': '',
     'fix_6_mths_max': '',
     'fix_6_mths_min': '',
     'period': '2021-08-02',
     'saving_max': '',
     'saving_min': ''},
    {'bank_name_eng': 'Citibank',
     'bank_name_th': 'ซิตี้แบงก์',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '0.2000',
     'fix_12_mths_min': '0.2000',
     'fix_24_mths_max': '0.2000',
     'fix_24_mths_min': '0.2000',
     'fix_3_mths_max': '0.4500',
     'fix_3_mths_min': '0.4500',
     'fix_6_mths_max': '0.2000',
     'fix_6_mths_min': '0.2000',
     'period': '2021-08-02',
     'saving_max': '0.1000',
     'saving_min': '0.1000'},
    {'bank_name_eng': 'Sumitomo Mitsui Banking Corporation',
     'bank_name_th': 'ซูมิโตโม มิตซุย แบงกิ้ง คอร์ปอร์เรชั่น',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '0.0800',
     'fix_12_mths_min': '0.0800',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '0.0600',
     'fix_3_mths_min': '0.0600',
     'fix_6_mths_max': '0.0800',
     'fix_6_mths_min': '0.0800',
     'period': '2021-08-02',
     'saving_max': '0.0500',
     'saving_min': '0.0500'},
    {'bank_name_eng': 'HONGKONG AND SHANGHAI BANKING CORPORATION',
     'bank_name_th': 'ฮ่องกงและเซี่ยงไฮ้แบงกิ้งคอร์ปอเรชั่น',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '',
     'fix_12_mths_min': '',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '',
     'fix_3_mths_min': '',
     'fix_6_mths_max': '',
     'fix_6_mths_min': '',
     'period': '2021-08-02',
     'saving_max': '',
     'saving_min': ''},
    {'bank_name_eng': 'Deutsche Bank AG.',
     'bank_name_th': 'ดอยซ์แบงก์',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '',
     'fix_12_mths_min': '',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '',
     'fix_3_mths_min': '',
     'fix_6_mths_max': '',
     'fix_6_mths_min': '',
     'period': '2021-08-02',
     'saving_max': '',
     'saving_min': ''},
    {'bank_name_eng': 'JP Morgan Chase Bank',
     'bank_name_th': 'เจพีมอร์แกน เชส',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '',
     'fix_12_mths_min': '',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '',
     'fix_3_mths_min': '',
     'fix_6_mths_max': '',
     'fix_6_mths_min': '',
     'period': '2021-08-02',
     'saving_max': '',
     'saving_min': ''},
    {'bank_name_eng': 'Bank of America, National Association',
     'bank_name_th': 'แห่งอเมริกาเนชั่นแนลแอสโซซิเอชั่น',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '',
     'fix_12_mths_min': '',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '',
     'fix_3_mths_min': '',
     'fix_6_mths_max': '',
     'fix_6_mths_min': '',
     'period': '2021-08-02',
     'saving_max': '',
     'saving_min': ''},
    {'bank_name_eng': 'Indian Overseas Bank',
     'bank_name_th': 'อินเดียนโอเวอร์ซีส์',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '0.8000',
     'fix_12_mths_min': '0.8000',
     'fix_24_mths_max': '0.8000',
     'fix_24_mths_min': '0.8000',
     'fix_3_mths_max': '0.4500',
     'fix_3_mths_min': '0.4500',
     'fix_6_mths_max': '0.7000',
     'fix_6_mths_min': '0.7000',
     'period': '2021-08-02',
     'saving_max': '0.3500',
     'saving_min': '0.3500'},
    {'bank_name_eng': 'RHB Bank Berhad',
     'bank_name_th': 'อาร์ เอช บี',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '1.3500',
     'fix_12_mths_min': '1.1500',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '0.8500',
     'fix_3_mths_min': '0.7500',
     'fix_6_mths_max': '1.0500',
     'fix_6_mths_min': '0.9500',
     'period': '2021-08-02',
     'saving_max': '0.7500',
     'saving_min': '0.5000'},
    {'bank_name_eng': 'Oversea Chinese Banking Corporation',
     'bank_name_th': 'โอเวอร์ซี-ไชนิสแบงกิ้งคอร์ปอเรชั่น',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '0.3500',
     'fix_12_mths_min': '0.3000',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '0.2000',
     'fix_3_mths_min': '0.1700',
     'fix_6_mths_max': '0.3300',
     'fix_6_mths_min': '0.3000',
     'period': '2021-08-02',
     'saving_max': '0.0250',
     'saving_min': '0.0250'},
    {'bank_name_eng': 'Mizuho Bank',
     'bank_name_th': 'มิซูโฮ',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '',
     'fix_12_mths_min': '',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '',
     'fix_3_mths_min': '',
     'fix_6_mths_max': '',
     'fix_6_mths_min': '',
     'period': '2021-08-02',
     'saving_max': '',
     'saving_min': ''},
    {'bank_name_eng': 'BNP Paribas',
     'bank_name_th': 'บีเอ็นพี พารีบาส์',
     'bank_type_name_eng': 'Foreign Bank Branches',
     'bank_type_name_th': 'สาขาธนาคารต่างประเทศ',
     'fix_12_mths_max': '',
     'fix_12_mths_min': '',
     'fix_24_mths_max': '',
     'fix_24_mths_min': '',
     'fix_3_mths_max': '',
     'fix_3_mths_min': '',
     'fix_6_mths_max': '',
     'fix_6_mths_min': '',
     'period': '2021-08-02',
     'saving_max': '',
     'saving_min': ''},
    {'bank_name_eng': 'Bangkok Bank',
     'bank_name_th': 'กรุงเทพ',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.5000',
     'fix_12_mths_min': '0.5000',
     'fix_24_mths_max': '0.5000',
     'fix_24_mths_min': '0.5000',
     'fix_3_mths_max': '0.3750',
     'fix_3_mths_min': '0.3750',
     'fix_6_mths_max': '0.5000',
     'fix_6_mths_min': '0.5000',
     'period': '2021-08-03',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'Krung Thai Bank',
     'bank_name_th': 'กรุงไทย',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.4000',
     'fix_12_mths_min': '0.4000',
     'fix_24_mths_max': '0.4500',
     'fix_24_mths_min': '0.4500',
     'fix_3_mths_max': '0.3200',
     'fix_3_mths_min': '0.3200',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-03',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'Kasikornbank',
     'bank_name_th': 'กสิกรไทย',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.4000',
     'fix_12_mths_min': '0.4000',
     'fix_24_mths_max': '0.4500',
     'fix_24_mths_min': '0.4500',
     'fix_3_mths_max': '0.3200',
     'fix_3_mths_min': '0.3200',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-03',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'The Siam Commercial Bank',
     'bank_name_th': 'ไทยพาณิชย์',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.4000',
     'fix_12_mths_min': '0.4000',
     'fix_24_mths_max': '0.4500',
     'fix_24_mths_min': '0.4500',
     'fix_3_mths_max': '0.3200',
     'fix_3_mths_min': '0.3200',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-03',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'Bank of Ayudhya',
     'bank_name_th': 'กรุงศรีอยุธยา',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.4000',
     'fix_12_mths_min': '0.4000',
     'fix_24_mths_max': '0.4500',
     'fix_24_mths_min': '0.4500',
     'fix_3_mths_max': '0.3200',
     'fix_3_mths_min': '0.3200',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-03',
     'saving_max': '0.2500',
     'saving_min': '0.2500'},
    {'bank_name_eng': 'TMBThanachart Bank Public Company Limited',
     'bank_name_th': 'ทหารไทยธนชาต',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.6000',
     'fix_12_mths_min': '0.6000',
     'fix_24_mths_max': '0.6000',
     'fix_24_mths_min': '0.6000',
     'fix_3_mths_max': '0.4000',
     'fix_3_mths_min': '0.4000',
     'fix_6_mths_max': '0.5000',
     'fix_6_mths_min': '0.5000',
     'period': '2021-08-03',
     'saving_max': '0.1250',
     'saving_min': '0.1250'},
    {'bank_name_eng': 'United Overseas Bank (Thai) Company Ltd.',
     'bank_name_th': 'ยูโอบี',
     'bank_type_name_eng': 'Commercial Banks registered in Thailand',
     'bank_type_name_th': 'ธนาคารพาณิชย์จดทะเบียนในประเทศ',
     'fix_12_mths_max': '0.5000',
     'fix_12_mths_min': '0.5000',
     'fix_24_mths_max': '0.6000',
     'fix_24_mths_min': '0.6000',
     'fix_3_mths_max': '0.4000',
     'fix_3_mths_min': '0.4000',
     'fix_6_mths_max': '0.4000',
     'fix_6_mths_min': '0.4000',
     'period': '2021-08-03',
     'saving_max': '0.2000',

# Hands on Web API

Create the data frame for "Deposit Interest Rates for Individuals of Commercial Banks (Percent per annum)"

In [58]:
df = pd.DataFrame(res_j['result']['data']['data_detail'])
df

         period               bank_type_name_th  ... fix_24_mths_min fix_24_mths_max
0    2021-08-02  ธนาคารพาณิชย์จดทะเบียนในประเทศ  ...          0.5000          0.5000
1    2021-08-02  ธนาคารพาณิชย์จดทะเบียนในประเทศ  ...          0.4500          0.4500
2    2021-08-02  ธนาคารพาณิชย์จดทะเบียนในประเทศ  ...          0.4500          0.4500
3    2021-08-02  ธนาคารพาณิชย์จดทะเบียนในประเทศ  ...          0.4500          0.4500
4    2021-08-02  ธนาคารพาณิชย์จดทะเบียนในประเทศ  ...          0.4500          0.4500
..          ...                             ...  ...             ...             ...
604  2021-08-31            สาขาธนาคารต่างประเทศ  ...          0.8000          0.8000
605  2021-08-31            สาขาธนาคารต่างประเทศ  ...
606  2021-08-31            สาขาธนาคารต่างประเทศ  ...
607  2021-08-31            สาขาธนาคารต่างประเทศ  ...
608  2021-08-31            สาขาธนาคารต่างประเทศ  ...

[609 rows x 15 columns]